apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: challenge

resources:
  - namespace.yaml
  - postgres.yaml
  - migration-job.yaml
  - app.yaml
  - servicemonitor.yaml

images:
  - name: platform-challenge
    newName: platform-challenge
    newTag: 0.1.0

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: platform-challenge

configMapGenerator:
  - name: app-dashboard
    files:
      - dashboards/platform-challenge.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
